import { arrayJoin } from 'src/utils/array';

export const LINK_CLICK_HIT_PROVIDER = '2';

export const METHOD_NAME_FILE_CLICK = 'file';
export const METHOD_NAME_EXTERNAL_LINK_CLICK = 'extLink';
export const METHOD_NAME_ADD_FILE_EXTENSION = 'addFileExtension';
export const METHOD_NAME_TRACK_LINKS = 'trackLinks';
export const INTERNAL_LINK_STORAGE_KEY = 'il';
export const MAX_LEN_INTERNAL_LINK = 100;
export const BAD_PROTOCOL_RE = /^\s*(data|javascript):/i;

export const REG_DOWNLOAD = new RegExp(
    arrayJoin('', [
        `\\.(${arrayJoin('|', [
            '3gp',
            '7z',
            'aac',
            'ac3',
            'acs',
            'ai',
            'avi',
            'ape',
            'apk',
            'asf',
            'bmp',
            'bz2',
            'cab',
            'cdr',
            'crc32',
            'css',
            'csv',
            'cue',
            'divx',
            'dmg',
            'djvu?',
            'doc(x|m|b)?',
            'emf',
            'eps',
            'exe',
            'flac?',
            'flv',
            'iso',
            'swf',
            'gif',
            't?gz',
            'jpe?g?',
            'js',
            'm3u8?',
            'm4a',
            'mp(3|4|e?g?)',
            'm4v',
            'md5',
            'mkv',
            'mov',
            'msi',
            'ods',
            'og(g|m|v)',
            'psd',
            'rar',
            'rss',
            'rtf',
            'sea',
            'sfv',
            'sit',
            'sha1',
            'svg',
            'tar',
            'tif?f',
            'torrent',
            'ts',
            'txt',
            'vob',
            'wave?',
            'wma',
            'wmv',
            'wmf',
            'webm',
            'ppt(x|m|b)?',
            'xls(x|m|b)?',
            'pdf',
            'phps',
            'png',
            'xpi',
            'g?zip',
        ])})$`,
    ]),
    'i',
);
